export const CREATE_MEETING = "CREATE_MEETING";
// export const UPDATE_MEETING = "UPDATE_MEETING";
export const FETCH_MEETING_DETAILS = "FETCH_MEETING_DETAILS";

export const ADD_MEETING = "ADD_MEETING";
export const EDIT_MEETING = "EDIT_MEETING";
export const UPDATE_MEETING = "UPDATE_MEETING";
